server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST_NAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:tea_shop}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:0987}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: false
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

tea:
  secret-key: 38792F423F4528472B4B6250655368566D597133743677397A24432646294A40
  expiration:
    token: 2592000
    refresh-token: P9W
  bonuses-percent: 0.05

s3config:
  endpoint: "your-endpoint"
  region: "your-region"
  bucket: "your-bucket"
  access: "your-access-id"
  key: "your-secret-key"